// Generic content-block widgets — not tied to any Hubzilla app or route.
// All are multiInstance + configurable and live only in user layouts
// (defaultModules: []), placeable on any module's pages.

import { registerModule } from "@utsukta/spa-core/module-registry";
import { useI18n } from "@utsukta/spa-core/i18n";

registerModule({
  id: "blocks",
  routes: [],
  widgets: [
    {
      id: "blocks.rss",
      label: () => useI18n().t("widgets.rss_feed"),
      loader: () => import("./widgets/RssWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/RssConfig"),
      helpTarget: "widgets.rss",
    },
    {
      id: "blocks.html",
      label: () => useI18n().t("widgets.html_block"),
      loader: () => import("./widgets/HtmlBlockWidget"),
      slot: ["right", "footer", "contentTop", "header"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/HtmlBlockConfig"),
      helpTarget: "widgets.html_block",
    },
    {
      id: "blocks.clock",
      label: () => useI18n().t("widgets.clock_card"),
      loader: () => import("./widgets/ClockWidget"),
      slot: ["right", "contentTop"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/ClockConfig"),
      helpTarget: "widgets.clock_card",
    },
    {
      // Owner productivity tool, not page content — hidden from visitors
      id: "blocks.pomodoro",
      label: () => useI18n().t("widgets.pomodoro"),
      loader: () => import("./widgets/PomodoroWidget"),
      slot: ["right", "contentTop"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      visitorVisible: false,
      configComponent: () => import("./widgets/PomodoroConfig"),
      helpTarget: "widgets.pomodoro",
    },
    {
      id: "blocks.weather",
      label: () => useI18n().t("widgets.weather"),
      loader: () => import("./widgets/WeatherWidget"),
      slot: ["right", "contentTop"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      helpTarget: "widgets.weather",
      configComponent: () => import("./widgets/WeatherConfig"),
    },
    {
      id: "blocks.quote",
      label: () => useI18n().t("widgets.quote_of_day"),
      loader: () => import("./widgets/QuoteWidget"),
      slot: ["right", "contentTop", "footer"],
      defaultModules: [],
      contexts: "any",
      helpTarget: "widgets.quotes",
      multiInstance: true,
    },
    {
      id: "blocks.embed",
      label: () => useI18n().t("widgets.embed"),
      loader: () => import("./widgets/EmbedWidget"),
      slot: ["right", "contentTop", "footer"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      helpTarget: "widgets.embed",
      configComponent: () => import("./widgets/EmbedConfig"),
    },
    {
      // Horizontal nav bar fed by a Hubzilla menu — header only (always
      // full-width by default, like every other contentTop widget)
      id: "blocks.menu_bar",
      label: () => useI18n().t("widgets.menu_bar"),
      loader: () => import("./widgets/MenuBarWidget"),
      slot: "header",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/MenuConfig"),
      helpTarget: "widgets.menu_bar",
    },
    {
      // Vertical multilevel menu fed by a Hubzilla menu — right sidebar only
      id: "blocks.menu_tree",
      label: () => useI18n().t("widgets.menu_tree"),
      loader: () => import("./widgets/MenuTreeWidget"),
      slot: ["right", "footer"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/MenuConfig"),
      helpTarget: "widgets.menu_tree",
    },
    {
      id: "blocks.links",
      label: () => useI18n().t("widgets.link_list"),
      loader: () => import("./widgets/LinkListWidget"),
      slot: ["right", "footer"],
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/LinkListConfig"),
      helpTarget: "widgets.link_list",
    },
  ],
  permissions: [],
});
